/**
 * System Configuration Registry
 * Defines every configurable value in the platform with metadata,
 * types, defaults, validation rules, and categorisation.
 */

export interface ConfigDefinition {
  key: string;
  category: ConfigCategory;
  label: string;
  description: string;
  type: "string" | "number" | "boolean" | "json" | "string[]";
  defaultValue: unknown;
  validation?: {
    min?: number;
    max?: number;
    pattern?: string;
    options?: string[];
  };
  sensitive?: boolean;
  restartRequired?: boolean;
}

export type ConfigCategory =
  | "storage"
  | "integrations"
  | "automations"
  | "media"
  | "rate_limits"
  | "operational"
  | "websocket"
  | "security"
  | "ai"
  | "connections"
  | "channels";

export const CONFIG_CATEGORY_LABELS: Record<ConfigCategory, string> = {
  storage: "Storage & Paths",
  integrations: "Integrations & Endpoints",
  automations: "Automation & Task Scheduling",
  media: "Media & File Handling",
  rate_limits: "Rate Limiting",
  operational: "Operational Rules",
  websocket: "WebSocket & Real-Time",
  security: "Security & HTTP",
  ai: "AI & LLM Settings",
  connections: "Connections & Services",
  channels: "Channels & Events",
};

export const CONFIG_REGISTRY: ConfigDefinition[] = [
  // ── Storage & Paths ──
  {
    key: "storage.document_base_dir",
    category: "storage",
    label: "Document Storage Directory",
    description: "Base directory for uploaded files. Relative to project root or absolute path.",
    type: "string",
    defaultValue: "uploads",
  },
  {
    key: "storage.exports_subdir",
    category: "storage",
    label: "Exports Subdirectory",
    description: "Subdirectory under document storage for generated exports.",
    type: "string",
    defaultValue: "exports",
  },
  {
    key: "storage.customer_photos_provider",
    category: "storage",
    label: "Customer Photo Upload Provider",
    description: "Storage backend for customer-uploaded photos (gdrive, dropbox, s3, webhook, local).",
    type: "string",
    defaultValue: "local",
    validation: { options: ["local", "gdrive", "dropbox", "s3", "webhook"] },
  },
  {
    key: "storage.customer_photos_folder",
    category: "storage",
    label: "Customer Photo Folder Path",
    description: "Target folder path for customer photo uploads in the selected provider.",
    type: "string",
    defaultValue: "/customer-photos",
  },
  {
    key: "storage.evidence_provider",
    category: "storage",
    label: "Evidence Upload Provider",
    description: "Storage backend for vehicle evidence photos (local, s3, gdrive).",
    type: "string",
    defaultValue: "local",
    validation: { options: ["local", "s3", "gdrive"] },
  },
  {
    key: "storage.evidence_folder",
    category: "storage",
    label: "Evidence Folder Path",
    description: "Target folder for vehicle evidence uploads.",
    type: "string",
    defaultValue: "/evidence",
  },

  // ── Integrations & Endpoints ──
  {
    key: "integrations.openai_base_url",
    category: "integrations",
    label: "OpenAI API Base URL",
    description: "Base URL for the OpenAI-compatible API.",
    type: "string",
    defaultValue: "https://api.openai.com/v1",
  },
  {
    key: "integrations.openrouter_base_url",
    category: "integrations",
    label: "OpenRouter API Base URL",
    description: "Base URL for OpenRouter API.",
    type: "string",
    defaultValue: "https://openrouter.ai/api/v1",
  },
  {
    key: "integrations.google_genai_base_url",
    category: "integrations",
    label: "Google Generative AI Base URL",
    description: "Base URL for Google Generative AI API.",
    type: "string",
    defaultValue: "https://generativelanguage.googleapis.com/v1beta/openai",
  },
  {
    key: "integrations.mistral_base_url",
    category: "integrations",
    label: "Mistral API Base URL",
    description: "Base URL for Mistral AI API.",
    type: "string",
    defaultValue: "https://api.mistral.ai/v1",
  },
  {
    key: "integrations.s3_endpoint",
    category: "integrations",
    label: "S3-Compatible Endpoint",
    description: "Endpoint URL for S3-compatible object storage.",
    type: "string",
    defaultValue: "",
  },
  {
    key: "integrations.s3_region",
    category: "integrations",
    label: "S3 Region",
    description: "AWS region or S3-compatible region identifier.",
    type: "string",
    defaultValue: "us-east-1",
  },
  {
    key: "integrations.webhook_delivery_url",
    category: "integrations",
    label: "Default Webhook Delivery URL",
    description: "Default URL endpoint for outbound webhook event delivery.",
    type: "string",
    defaultValue: "",
  },

  // ── Connections & Services ──
  {
    key: "connections.google_workspace_enabled",
    category: "connections",
    label: "Google Workspace Integration",
    description: "Enable Google Workspace (Drive, Calendar) integration.",
    type: "boolean",
    defaultValue: false,
  },
  {
    key: "connections.google_drive_folder_id",
    category: "connections",
    label: "Google Drive Target Folder ID",
    description: "Google Drive folder ID for file uploads and sync.",
    type: "string",
    defaultValue: "",
  },
  {
    key: "connections.email_smtp_host",
    category: "connections",
    label: "SMTP Server Host",
    description: "SMTP server hostname for outbound email delivery.",
    type: "string",
    defaultValue: "",
  },
  {
    key: "connections.email_smtp_port",
    category: "connections",
    label: "SMTP Server Port",
    description: "SMTP server port number.",
    type: "number",
    defaultValue: 587,
    validation: { min: 1, max: 65535 },
  },
  {
    key: "connections.email_from_address",
    category: "connections",
    label: "Email From Address",
    description: "Default sender address for outbound emails.",
    type: "string",
    defaultValue: "",
  },
  {
    key: "connections.sms_provider",
    category: "connections",
    label: "SMS Provider",
    description: "SMS gateway provider for outbound messages.",
    type: "string",
    defaultValue: "none",
    validation: { options: ["none", "twilio", "vonage", "webhook"] },
  },
  {
    key: "connections.sms_webhook_url",
    category: "connections",
    label: "SMS Webhook URL",
    description: "Webhook URL for custom SMS gateway integration.",
    type: "string",
    defaultValue: "",
  },

  // ── Automation & Task Scheduling ──
  {
    key: "automations.sla_breach_interval_ms",
    category: "automations",
    label: "SLA Breach Check Interval (ms)",
    description: "How often the SLA breach checker runs.",
    type: "number",
    defaultValue: 60000,
    validation: { min: 10000, max: 3600000 },
  },
  {
    key: "automations.sla_breach_timeout_ms",
    category: "automations",
    label: "SLA Breach Check Timeout (ms)",
    description: "Maximum execution time for a single SLA breach check run.",
    type: "number",
    defaultValue: 30000,
    validation: { min: 5000, max: 120000 },
  },
  {
    key: "automations.kpi_snapshot_interval_ms",
    category: "automations",
    label: "KPI Snapshot Interval (ms)",
    description: "How often KPI snapshots are generated.",
    type: "number",
    defaultValue: 14400000,
    validation: { min: 300000, max: 86400000 },
  },
  {
    key: "automations.anomaly_detection_interval_ms",
    category: "automations",
    label: "Anomaly Detection Interval (ms)",
    description: "How often the anomaly detection task runs.",
    type: "number",
    defaultValue: 900000,
    validation: { min: 60000, max: 3600000 },
  },
  {
    key: "automations.connector_sync_interval_ms",
    category: "automations",
    label: "Connector Sync Interval (ms)",
    description: "How often external connector synchronisation runs.",
    type: "number",
    defaultValue: 600000,
    validation: { min: 60000, max: 3600000 },
  },
  {
    key: "automations.export_processor_interval_ms",
    category: "automations",
    label: "Export Processor Interval (ms)",
    description: "How often the export job processor checks for pending exports.",
    type: "number",
    defaultValue: 30000,
    validation: { min: 5000, max: 300000 },
  },
  {
    key: "automations.export_cleanup_interval_ms",
    category: "automations",
    label: "Export Cleanup Interval (ms)",
    description: "How often expired exports are cleaned up.",
    type: "number",
    defaultValue: 900000,
    validation: { min: 60000, max: 86400000 },
  },
  {
    key: "automations.default_task_timeout_ms",
    category: "automations",
    label: "Default Task Timeout (ms)",
    description: "Default timeout for background tasks if not overridden.",
    type: "number",
    defaultValue: 30000,
    validation: { min: 5000, max: 300000 },
  },

  // ── Media & File Handling ──
  {
    key: "media.max_upload_size_bytes",
    category: "media",
    label: "Max File Upload Size (bytes)",
    description: "Maximum allowed file size for uploads. Default 25 MB.",
    type: "number",
    defaultValue: 25 * 1024 * 1024,
    validation: { min: 1024, max: 500 * 1024 * 1024 },
  },
  {
    key: "media.allowed_mime_types",
    category: "media",
    label: "Allowed MIME Types",
    description: "Comma-separated list of allowed MIME types for file uploads.",
    type: "string[]",
    defaultValue: [
      "image/jpeg", "image/png", "image/webp", "image/gif",
      "application/pdf", "text/csv", "text/plain",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "application/vnd.ms-excel",
    ],
  },
  {
    key: "media.max_telematics_payload_bytes",
    category: "media",
    label: "Max Telematics Payload Size (bytes)",
    description: "Maximum allowed size for a single telematics event payload.",
    type: "number",
    defaultValue: 65536,
    validation: { min: 1024, max: 1048576 },
  },
  {
    key: "media.image_compression_quality",
    category: "media",
    label: "Image Compression Quality",
    description: "JPEG/WebP compression quality (0-100) for processed images.",
    type: "number",
    defaultValue: 85,
    validation: { min: 10, max: 100 },
  },

  // ── Rate Limiting ──
  {
    key: "rate_limits.auth_window_minutes",
    category: "rate_limits",
    label: "Auth Rate Limit Window (minutes)",
    description: "Time window for authentication rate limiting.",
    type: "number",
    defaultValue: 15,
    validation: { min: 1, max: 60 },
    restartRequired: true,
  },
  {
    key: "rate_limits.auth_max_attempts",
    category: "rate_limits",
    label: "Auth Max Attempts",
    description: "Maximum authentication attempts per window.",
    type: "number",
    defaultValue: 20,
    validation: { min: 3, max: 100 },
    restartRequired: true,
  },
  {
    key: "rate_limits.api_window_minutes",
    category: "rate_limits",
    label: "API Rate Limit Window (minutes)",
    description: "Time window for general API rate limiting.",
    type: "number",
    defaultValue: 1,
    validation: { min: 1, max: 60 },
    restartRequired: true,
  },
  {
    key: "rate_limits.api_max_requests",
    category: "rate_limits",
    label: "API Max Requests Per Window",
    description: "Maximum API requests per window per user/IP.",
    type: "number",
    defaultValue: 100,
    validation: { min: 10, max: 10000 },
    restartRequired: true,
  },
  {
    key: "rate_limits.ai_chat_window_minutes",
    category: "rate_limits",
    label: "AI Chat Rate Limit Window (minutes)",
    description: "Time window for AI chat rate limiting.",
    type: "number",
    defaultValue: 1,
    validation: { min: 1, max: 60 },
    restartRequired: true,
  },
  {
    key: "rate_limits.ai_chat_max_requests",
    category: "rate_limits",
    label: "AI Chat Max Requests Per Window",
    description: "Maximum AI chat requests per window.",
    type: "number",
    defaultValue: 10,
    validation: { min: 1, max: 100 },
    restartRequired: true,
  },
  {
    key: "rate_limits.search_max_requests",
    category: "rate_limits",
    label: "Search Max Requests Per Minute",
    description: "Maximum search requests per minute.",
    type: "number",
    defaultValue: 30,
    validation: { min: 5, max: 500 },
    restartRequired: true,
  },
  {
    key: "rate_limits.wash_queue_read_max",
    category: "rate_limits",
    label: "Wash Queue Read Max Requests/min",
    description: "Maximum wash queue read requests per minute.",
    type: "number",
    defaultValue: 60,
    validation: { min: 10, max: 500 },
    restartRequired: true,
  },
  {
    key: "rate_limits.wash_queue_write_max",
    category: "rate_limits",
    label: "Wash Queue Write Max Requests/min",
    description: "Maximum wash queue write requests per minute.",
    type: "number",
    defaultValue: 10,
    validation: { min: 1, max: 100 },
    restartRequired: true,
  },
  {
    key: "rate_limits.evidence_upload_max",
    category: "rate_limits",
    label: "Evidence Upload Max Requests/min",
    description: "Maximum evidence upload requests per minute.",
    type: "number",
    defaultValue: 5,
    validation: { min: 1, max: 50 },
    restartRequired: true,
  },
  {
    key: "rate_limits.webhooks_max_requests",
    category: "rate_limits",
    label: "Webhooks Max Requests/min",
    description: "Maximum webhook requests per minute.",
    type: "number",
    defaultValue: 30,
    validation: { min: 5, max: 500 },
    restartRequired: true,
  },

  // ── Operational Rules ──
  {
    key: "operational.max_export_rows",
    category: "operational",
    label: "Max Export Rows Per File",
    description: "Maximum number of rows in a single export file.",
    type: "number",
    defaultValue: 50000,
    validation: { min: 100, max: 1000000 },
  },
  {
    key: "operational.export_expiry_hours",
    category: "operational",
    label: "Export File Expiry (hours)",
    description: "Hours before exported files are automatically deleted.",
    type: "number",
    defaultValue: 48,
    validation: { min: 1, max: 720 },
  },
  {
    key: "operational.telematics_batch_size",
    category: "operational",
    label: "Telematics Batch Size",
    description: "Maximum events per telematics ingestion batch.",
    type: "number",
    defaultValue: 500,
    validation: { min: 10, max: 10000 },
  },
  {
    key: "operational.max_macro_steps",
    category: "operational",
    label: "Max Macro Steps",
    description: "Maximum number of steps allowed in a workspace macro.",
    type: "number",
    defaultValue: 10,
    validation: { min: 1, max: 100 },
  },
  {
    key: "operational.activity_retention_days",
    category: "operational",
    label: "Activity Log Retention (days)",
    description: "Default number of days to retain activity feed entries.",
    type: "number",
    defaultValue: 90,
    validation: { min: 7, max: 3650 },
  },
  {
    key: "operational.anomaly_lookback_days",
    category: "operational",
    label: "Anomaly Detection Lookback (days)",
    description: "Number of days of historical data for anomaly detection baseline.",
    type: "number",
    defaultValue: 7,
    validation: { min: 1, max: 90 },
  },
  {
    key: "operational.anomaly_recent_window_minutes",
    category: "operational",
    label: "Anomaly Recent Window (minutes)",
    description: "Recent time window to compare against baseline for anomaly detection.",
    type: "number",
    defaultValue: 60,
    validation: { min: 5, max: 1440 },
  },
  {
    key: "operational.entitlements_cache_ttl_ms",
    category: "operational",
    label: "Entitlements Cache TTL (ms)",
    description: "How long entitlement checks are cached in memory.",
    type: "number",
    defaultValue: 30000,
    validation: { min: 1000, max: 300000 },
  },
  {
    key: "operational.wash_stagnation_hours",
    category: "operational",
    label: "Wash Stagnation Threshold (hours)",
    description: "Number of hours a wash item must be pending before it's flagged as stagnant.",
    type: "number",
    defaultValue: 4,
    validation: { min: 1, max: 48 },
  },
  {
    key: "operational.notification_spike_threshold",
    category: "operational",
    label: "Notification Spike Threshold",
    description: "Number of notifications in the recent window that triggers a spike anomaly.",
    type: "number",
    defaultValue: 20,
    validation: { min: 5, max: 500 },
  },
  {
    key: "operational.capabilities_cache_ttl_ms",
    category: "operational",
    label: "Capabilities Cache TTL (ms)",
    description: "How long capability checks are cached in memory.",
    type: "number",
    defaultValue: 30000,
    validation: { min: 1000, max: 300000 },
  },

  // ── AI & LLM Settings ──
  {
    key: "ai.max_messages_per_request",
    category: "ai",
    label: "Max Messages Per AI Request",
    description: "Maximum number of conversation messages sent to the LLM per request.",
    type: "number",
    defaultValue: 20,
    validation: { min: 1, max: 100 },
  },
  {
    key: "ai.max_chars_per_message",
    category: "ai",
    label: "Max Chars Per Message",
    description: "Maximum character length for a single user message to the AI.",
    type: "number",
    defaultValue: 4000,
    validation: { min: 100, max: 50000 },
  },
  {
    key: "ai.max_total_chars_per_request",
    category: "ai",
    label: "Max Total Chars Per AI Request",
    description: "Maximum total characters across all messages in a single AI request.",
    type: "number",
    defaultValue: 40000,
    validation: { min: 1000, max: 500000 },
  },
  {
    key: "ai.max_response_tokens",
    category: "ai",
    label: "Max AI Response Tokens",
    description: "Maximum tokens the AI model can generate in a single response.",
    type: "number",
    defaultValue: 1024,
    validation: { min: 64, max: 32768 },
  },
  {
    key: "ai.default_model",
    category: "ai",
    label: "Default AI Model",
    description: "Default LLM model identifier for AI chat.",
    type: "string",
    defaultValue: "gpt-4o-mini",
  },
  {
    key: "ai.system_prompt_override",
    category: "ai",
    label: "AI System Prompt Override",
    description: "Custom system prompt prepended to all AI conversations. Leave empty to use default.",
    type: "string",
    defaultValue: "",
  },

  // ── WebSocket & Real-Time ──
  {
    key: "websocket.heartbeat_interval_ms",
    category: "websocket",
    label: "Heartbeat Interval (ms)",
    description: "Interval for WebSocket heartbeat pings to keep connections alive.",
    type: "number",
    defaultValue: 30000,
    validation: { min: 5000, max: 120000 },
    restartRequired: true,
  },
  {
    key: "websocket.public_channels",
    category: "websocket",
    label: "Public WebSocket Channels",
    description: "List of public WebSocket channel names all clients can subscribe to.",
    type: "string[]",
    defaultValue: ["vehicles", "wash-queue", "activity", "notifications"],
  },

  // ── Security & HTTP ──
  {
    key: "security.json_body_size_limit",
    category: "security",
    label: "JSON Body Size Limit",
    description: "Maximum allowed JSON request body size (e.g. '1mb', '5mb').",
    type: "string",
    defaultValue: "1mb",
    restartRequired: true,
  },
  {
    key: "security.hsts_max_age_seconds",
    category: "security",
    label: "HSTS Max Age (seconds)",
    description: "HTTP Strict Transport Security max-age header value.",
    type: "number",
    defaultValue: 31536000,
    validation: { min: 0, max: 63072000 },
    restartRequired: true,
  },
  {
    key: "security.session_cookie_max_age_days",
    category: "security",
    label: "Session Cookie Max Age (days)",
    description: "Number of days before login session cookies expire.",
    type: "number",
    defaultValue: 30,
    validation: { min: 1, max: 365 },
    restartRequired: true,
  },
  {
    key: "security.trust_proxy_level",
    category: "security",
    label: "Trust Proxy Level",
    description: "Express trust proxy setting (number of proxy hops to trust).",
    type: "number",
    defaultValue: 1,
    validation: { min: 0, max: 10 },
    restartRequired: true,
  },

  // ── Channels & Events ──
  {
    key: "channels.notification_cooldown_seconds",
    category: "channels",
    label: "Notification Cooldown (seconds)",
    description: "Minimum time between duplicate notification events for the same vehicle/entity.",
    type: "number",
    defaultValue: 300,
    validation: { min: 10, max: 3600 },
  },
  {
    key: "channels.incident_cooldown_seconds",
    category: "channels",
    label: "Incident Cooldown (seconds)",
    description: "Minimum time between duplicate incident creation for the same trigger.",
    type: "number",
    defaultValue: 1800,
    validation: { min: 60, max: 86400 },
  },
  {
    key: "channels.default_cooldown_seconds",
    category: "channels",
    label: "Default Event Cooldown (seconds)",
    description: "Default cooldown between duplicate event processing.",
    type: "number",
    defaultValue: 60,
    validation: { min: 5, max: 3600 },
  },
  {
    key: "channels.customer_chat_enabled",
    category: "channels",
    label: "Customer Chat Channel",
    description: "Enable real-time chat channel for customer portal.",
    type: "boolean",
    defaultValue: true,
  },
  {
    key: "channels.washer_chat_enabled",
    category: "channels",
    label: "Washer Chat Channel",
    description: "Enable real-time chat channel for washer kiosk portal.",
    type: "boolean",
    defaultValue: true,
  },
  {
    key: "channels.reservation_auto_link",
    category: "channels",
    label: "Auto-Link Reservations to Channels",
    description: "Automatically create a communication channel for each new reservation.",
    type: "boolean",
    defaultValue: false,
  },
];

/** Lookup map for fast key-based access */
export const CONFIG_MAP = new Map(CONFIG_REGISTRY.map((d) => [d.key, d]));

/** Get the default value for a config key */
export function getConfigDefault(key: string): unknown {
  return CONFIG_MAP.get(key)?.defaultValue;
}
